### ISSUE TITLE
epochs value not updatable from the CLI arg query

### ISSUE THREAD

**Issue by mprichard** [skafos/parago-cli#5]
This was using the turicreate-imageclassifier generator.

ran: `pgo train --env epochs=20,batch_size=32,gpu=1`

the training output said: `Training the image classifier for 10 epochs with in batches of 32`

It looks like `gpu` and `batch_size` were updated through CLI, not epochs.

**Comment by tylerhutcherson** [comment]
Closing this issue as this was addressed in parago release 0.0.4. Thanks!
